### YamlMime:QSharpType
uid: microsoft.quantum.canon.compose
name: Compose
type: function
namespace: Microsoft.Quantum.Canon
summary: >-
  Generuje kompozycję dwóch funkcji.


  Oznacza to, że w przypadku dwóch funkcji $f $ i $g $, zwraca nową funkcję reprezentującą $f \circ g $.
syntax: "function Compose (outer : ('U -> 'V), inner : ('T -> 'U)) : ('T -> 'V)"
input:
  content: "(outer : ('U -> 'V), inner : ('T -> 'U))"
  types:
  - name: outer
    summary: Druga funkcja, która ma zostać zastosowana.
    isFunction: true
    input:
      types:
      - uid: "'U"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
  - name: inner
    summary: Pierwsza funkcja, która ma zostać zastosowana.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'U"
        isLocal: true
output:
  content: ('T -> 'V)
  types:
  - summary: Nowa funkcja $h $, która dla wszystkich wejść $x $, $f (g (x)) = h (x) $.
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
typeParameters:
- uid: "'T"
  summary: Typ wejścia pierwszej funkcji, która ma zostać zastosowana.
- uid: "'U"
  summary: Typ wyjściowy pierwszej funkcji, która ma zostać zastosowana i typ wejściowy drugiej funkcji, która ma zostać zastosowana.
- uid: "'V"
  summary: Typ wyjściowy drugiej funkcji, która ma zostać zastosowana.
ms.openlocfilehash: 69fbd6a4fafbc61a63e41257b7100303fd48d4d4
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 10/31/2019
ms.locfileid: "73223075"
